import copy

import pytest
from unittest.mock import AsyncMock, MagicMock

from app.game.match_runner import (MatchRunner,BehaviorExecutorProtocol,GameEngineProtocol)
from app.game.models.ball import Ball
from app.game.models.match import Match, MatchState
from app.game.models.match_participation import MatchParticipation


@pytest.fixture
def match(six_players):
    # create independent players for each team.
    players_a = copy.deepcopy(six_players)
    players_b = copy.deepcopy(six_players)

    # players from both teams must have different ids.
    for player in players_b:
        player.player_id += 6

    participation_a = MatchParticipation(
        club_id=1,
        roster_id=1,
        players=players_a,
    )

    participation_b = MatchParticipation(
        club_id=2,
        roster_id=2,
        players=players_b,
    )

    return Match(
        match_id=1,
        participation_a=participation_a,
        participation_b=participation_b,
        ball=Ball(
            position=(20.0, 10.0),
            velocity=(0.0, 0.0),
        ),
        duration_ticks=10,
    )

# we create a magicmock and assign it the attributes/methods of the class in spec
@pytest.fixture
def behavior_executor():
    executor = MagicMock(
        spec=BehaviorExecutorProtocol
    )

    # execute_all is asynchronous.
    executor.execute_all = AsyncMock(
        return_value=["wait"] * 6
    )

    return executor


@pytest.fixture
def game_engine():
    return MagicMock(
        spec=GameEngineProtocol
    )


@pytest.mark.asyncio
async def test_execute_tick_advances_one_tick(match,behavior_executor,game_engine):
    initial_tick = match.current_tick

    # prepare a MatchRunner
    runner = MatchRunner(
        behavior_executor,
        game_engine,
    )
    # and execute one tick
    await runner.execute_tick(match)

    assert match.current_tick == initial_tick + 1

@pytest.mark.asyncio
async def test_run_match_executes_behaviors_once_per_tick(match,behavior_executor,game_engine):
    match.duration_ticks = 3

    runner = MatchRunner(
        behavior_executor,
        game_engine,
    )

    # execute the entire match
    await runner.run_match(match)
    # use magicmock functionrs to count
    assert behavior_executor.execute_all.await_count == 3

@pytest.mark.asyncio
async def test_behavior_executor_and_engine_use_same_snapshot(
    match,
    behavior_executor,
    game_engine,
):
    runner = MatchRunner(
        behavior_executor,
        game_engine,
    )

    await runner.execute_tick(match)

    # use magic mock functiorns
    # we get the first argument with which it went inside execute tick
    snapshot_received_by_behavior_executor = (
        behavior_executor
        .execute_all
        .await_args
        .args[0]
    )

    # we get the second argument with which it went inside execute tick
    snapshot_received_by_engine = (
        game_engine
        .step
        .call_args
        .args[1]
    )

    assert (snapshot_received_by_behavior_executor is snapshot_received_by_engine)

@pytest.mark.asyncio
async def test_actions_are_sent_to_engine(
    match,
    behavior_executor,
    game_engine,
):
    runner = MatchRunner(
        behavior_executor,
        game_engine,
    )

    await runner.execute_tick(match)

    actions_received_by_engine = (
        game_engine
        .step
        .call_args
        .args[2]
    )

    assert actions_received_by_engine == ["wait"] * 6

@pytest.mark.asyncio
async def test_generated_state_is_used_in_next_tick(
    match,
    behavior_executor,
    game_engine,
):
    # change the duration only for this test
    match.duration_ticks = 2

    initial_ball_position = match.ball.position

    # the real engine is not implemented yet,
    # so we simulate that it changes the state of the ball.
    def engine_step(match, snapshot, actions):
        match.ball.position = (
            snapshot.ball.position[0] + 1,
            snapshot.ball.position[1],
        )

    game_engine.step.side_effect = engine_step

    runner = MatchRunner(
        behavior_executor,
        game_engine,
    )

    await runner.run_match(match)

    first_snapshot = (
        behavior_executor
        .execute_all
        .await_args_list[0]
        .args[0]
    )

    second_snapshot = (
        behavior_executor
        .execute_all
        .await_args_list[1]
        .args[0]
    )

    # state used for the first tick.
    assert first_snapshot.current_tick == 0
    assert first_snapshot.ball.position == initial_ball_position

    # state generated by the first tick is used by the second tick.
    assert second_snapshot.current_tick == 1

    assert second_snapshot.ball.position == (
        initial_ball_position[0] + 1,
        initial_ball_position[1],
    )

@pytest.mark.asyncio
async def test_run_match_stops_at_duration_ticks(
    match,
    behavior_executor,
    game_engine,
):

    runner = MatchRunner(
        behavior_executor,
        game_engine,
    )

    await runner.run_match(match)
    # wait for the match to end and then verify
    assert match.current_tick == 10

    assert behavior_executor.execute_all.await_count == 10
    assert game_engine.step.call_count == 10

    assert match.state == MatchState.FINISHED