"""add missing friendly game tables

Revision ID: 98c6ee7ce9cf
Revises: 62d4633c8641
Create Date: 2026-10-04 02:48:41.276680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98c6ee7ce9cf'
down_revision: Union[str, Sequence[str], None] = '62d4633c8641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendly_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('POR_COMENZAR', 'JUGANDO', 'FINALIZADO', name='friendlygamestate'), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('duration > 0', name='ck_friendly_game_duration_positive'),
    sa.ForeignKeyConstraint(['creator_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('power', sa.Integer(), nullable=False),
    sa.Column('agility', sa.Integer(), nullable=False),
    sa.Column('control', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.CheckConstraint('agility BETWEEN 20 AND 100', name='ck_player_agility_range'),
    sa.CheckConstraint('control BETWEEN 20 AND 100', name='ck_player_control_range'),
    sa.CheckConstraint('power + agility + control + speed + strength <= 300', name='ck_player_total_stats'),
    sa.CheckConstraint('power BETWEEN 20 AND 100', name='ck_player_power_range'),
    sa.CheckConstraint('speed BETWEEN 20 AND 100', name='ck_player_speed_range'),
    sa.CheckConstraint('strength BETWEEN 20 AND 100', name='ck_player_strength_range'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rosters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('formation', sa.Enum('DEFENSIVE', 'OFFENSIVE', name='formation'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friendly_game_participations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('friendly_game_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('roster_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('CREATOR', 'GUEST', name='friendlygamerole'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['friendly_game_id'], ['friendly_games.id'], ),
    sa.ForeignKeyConstraint(['roster_id'], ['rosters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('friendly_game_id', 'club_id', name='uq_friendly_game_club'),
    sa.UniqueConstraint('friendly_game_id', 'role', name='uq_friendly_game_role')
    )
    op.create_table('players_on_roster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roster_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('is_starter', sa.Boolean(), nullable=False),
    sa.Column('slot', sa.Enum('LEFT', 'CENTER', 'RIGHT', name='rosterslot'), nullable=True),
    sa.Column('initial_behavior_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['initial_behavior_id'], ['behaviors.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['roster_id'], ['rosters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players_on_roster')
    op.drop_table('friendly_game_participations')
    op.drop_table('rosters')
    op.drop_table('players')
    op.drop_table('friendly_games')
    # ### end Alembic commands ###
