"""Modificamos la taba user

Revision ID: baf356971275
Revises: 944c5f173f2c
Create Date: 2026-10-01 09:45:30.021011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baf356971275'
down_revision: Union[str, Sequence[str], None] = '944c5f173f2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('hash_passwd', sa.String(length=97), nullable=False))
        batch_op.add_column(sa.Column('avatar', sa.String(length=50), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_account_email'), ['email'], unique=True)
        batch_op.drop_column('passwdhash')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passwdhash', sa.VARCHAR(length=97), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_user_account_email'))
        batch_op.drop_column('avatar')
        batch_op.drop_column('hash_passwd')
        batch_op.drop_column('username')
    # ### end Alembic commands ###
