"""Separacion entre user y club

Revision ID: bf7182d25923
Revises: baf356971275
Create Date: 2026-10-01 20:52:39.651598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf7182d25923'
down_revision: Union[str, Sequence[str], None] = 'baf356971275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('avatar', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.alter_column('hash_passwd',
               existing_type=sa.VARCHAR(length=97),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_column('avatar')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('avatar', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.alter_column('hash_passwd',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=97),
               existing_nullable=False)

    op.drop_table('club')
    # ### end Alembic commands ###
